import 'dart:convert';

/// Everything about a setup that cannot be fetched again.
///
/// tvOS gives an app about half a megabyte of storage it will not reclaim,
/// and the catalogue is two hundred megabytes — so the catalogue lives in
/// `Library/Caches` and the system is entitled to delete it whenever it wants
/// the space. That is the right place for it: a catalogue is a copy of the
/// provider's listing and one sync rebuilds it.
///
/// Three kinds of thing survive a purge differently. Secrets are in the
/// keystore, which is not purged. Watch history is in the viewer's own backup
/// folder, which is not on the device at all. What was left is this: which
/// portal, which account, and which bucket — a few hundred bytes that are not
/// secret, cannot be derived, and were sitting in the one file the system is
/// allowed to throw away. Without them a purged device holds a keystore full
/// of passwords and no idea what they are for, and cannot even find the
/// folder its history is in.
///
/// So it goes in the keystore beside the secrets. Not because it is one — the
/// address and account name are not — but because that is the only durable
/// store the platform offers.
class RecoverySnapshot {
  const RecoverySnapshot({
    this.sources = const [],
    this.backup,
    this.watched = const [],
  });

  final List<RecoveredSource> sources;

  /// Where the backup folder is. Null when none is set up.
  final RecoveredBackup? backup;

  /// What has been watched and kept, newest first.
  ///
  /// Carried because without a folder there is nowhere else for it. A folder
  /// is the real answer — it is the only one that crosses devices — and a
  /// viewer who has not set one up should still not lose a year of positions
  /// to the system reclaiming disk space.
  ///
  /// A floor rather than an archive. The keystore is not built for bulk, so
  /// this is capped at the most recent few hundred; measured against a real
  /// device it is 74 bytes a row, so five hundred is under forty kilobytes.
  final List<RecoveredState> watched;

  /// How many positions are worth keeping.
  ///
  /// Favourites are not capped by this: there are few of them and nothing
  /// regenerates one, where a position is regenerated by watching.
  static const watchedCap = 500;

  bool get isEmpty => sources.isEmpty && backup == null && watched.isEmpty;

  String encode() => jsonEncode({
        'version': 1,
        'sources': [for (final source in sources) source.toJson()],
        if (backup case final held?) 'backup': held.toJson(),
        if (watched.isNotEmpty)
          'watched': [for (final state in watched) state.toJson()],
      });

  /// Reads a record back, or an empty one from anything unreadable.
  ///
  /// A record that cannot be parsed must not stop the app: the worst it can
  /// mean is that a viewer sets their provider up again, which is exactly
  /// what happens without it.
  static RecoverySnapshot decode(String? raw) {
    if (raw == null || raw.isEmpty) return const RecoverySnapshot();
    try {
      final json = jsonDecode(raw);
      if (json is! Map) return const RecoverySnapshot();
      final backup = json['backup'];
      return RecoverySnapshot(
        sources: [
          for (final entry in (json['sources'] as List? ?? const []))
            if (entry is Map) RecoveredSource.fromJson(entry.cast()),
        ],
        backup: backup is Map ? RecoveredBackup.fromJson(backup.cast()) : null,
        watched: [
          for (final entry in (json['watched'] as List? ?? const []))
            if (entry is Map) RecoveredState.fromJson(entry.cast()),
        ],
      );
    } on Object {
      return const RecoverySnapshot();
    }
  }
}

/// One provider, in the terms needed to add it back.
class RecoveredSource {
  const RecoveredSource({
    required this.name,
    required this.kind,
    required this.url,
    this.username,
    this.credentialRef,
    this.epgUrl,
  });

  final String name;

  /// `xtream` or `m3u`, as the enum names them. A string rather than the enum
  /// so a record written by a newer build is skipped rather than fatal.
  final String kind;

  final String url;
  final String? username;

  /// The keystore handle for the password. Not the password: that is already
  /// in the keystore and survives on its own. Without the handle, though, it
  /// is a secret nothing knows the purpose of.
  final String? credentialRef;

  final String? epgUrl;

  Map<String, Object?> toJson() => {
        'name': name,
        'kind': kind,
        'url': url,
        if (username != null) 'username': username,
        if (credentialRef != null) 'credentialRef': credentialRef,
        if (epgUrl != null) 'epgUrl': epgUrl,
      };

  static RecoveredSource fromJson(Map<String, Object?> json) => RecoveredSource(
        name: json['name'] as String? ?? 'Provider',
        kind: json['kind'] as String? ?? 'xtream',
        url: json['url'] as String? ?? '',
        username: json['username'] as String?,
        credentialRef: json['credentialRef'] as String?,
        epgUrl: json['epgUrl'] as String?,
      );
}

/// Where the shared folder is. The keys themselves are already in the
/// keystore under their own references.
class RecoveredBackup {
  const RecoveredBackup({
    required this.endpoint,
    required this.bucket,
    this.region,
  });

  final String endpoint;
  final String bucket;
  final String? region;

  Map<String, Object?> toJson() => {
        'endpoint': endpoint,
        'bucket': bucket,
        if (region != null && region!.isNotEmpty) 'region': region,
      };

  static RecoveredBackup fromJson(Map<String, Object?> json) =>
      RecoveredBackup(
        endpoint: json['endpoint'] as String? ?? '',
        bucket: json['bucket'] as String? ?? '',
        region: json['region'] as String?,
      );
}


/// One thing watched, or one thing kept, in terms that outlive the row.
///
/// Keyed on [provider] — a hash of the portal address and the account — and
/// never on `Sources.id`, which is an autoincrement and is a different number
/// the moment the source is added back. That is the same identity the backup
/// folder uses, for the same reason.
class RecoveredState {
  const RecoveredState({
    required this.provider,
    required this.kind,
    required this.remoteId,
    required this.at,
    this.favourite = false,
    this.positionMs,
    this.durationMs,
    this.parentRemoteId,
    this.completed = false,
  });

  final String provider;

  /// `live`, `movie`, `series` or `episode`, as the enum names them.
  final String kind;

  final String remoteId;

  /// When it was watched, or when it was kept. Preserved rather than reset to
  /// the moment of the restore: a shelf ordered by "most recent" would
  /// otherwise come back in whatever order the rows were written.
  final DateTime at;

  /// True for something kept rather than something watched.
  final bool favourite;

  final int? positionMs;
  final int? durationMs;
  final String? parentRemoteId;
  final bool completed;

  Map<String, Object?> toJson() => {
        'p': provider,
        'k': kind,
        'r': remoteId,
        'a': at.toUtc().millisecondsSinceEpoch,
        if (favourite) 'f': true,
        if (positionMs != null) 'ms': positionMs,
        if (durationMs != null) 'd': durationMs,
        if (parentRemoteId != null) 'pa': parentRemoteId,
        if (completed) 'c': true,
      };

  static RecoveredState fromJson(Map<String, Object?> json) => RecoveredState(
        provider: json['p'] as String? ?? '',
        kind: json['k'] as String? ?? '',
        remoteId: json['r'] as String? ?? '',
        at: DateTime.fromMillisecondsSinceEpoch(
          (json['a'] as int?) ?? 0,
          isUtc: true,
        ),
        favourite: json['f'] == true,
        positionMs: json['ms'] as int?,
        durationMs: json['d'] as int?,
        parentRemoteId: json['pa'] as String?,
        completed: json['c'] == true,
      );
}
