package com.anthonyessaye.opentv.Models.Series

import java.io.Serializable

data class EpisodeVideo(val index: Int,
                        val codec_name: String,
                        val codec_long_name: String,
                        val profile: String,
                        val codec_type: String,
                        val codec_tag_string: String,
                        val codec_tag: String,
                        val width: Int,
                        val height: Int,
                        val coded_width: Int,
                        val coded_height: Int,
                        val closed_captions: Int,
                        val film_grain: Int,
                        val has_b_frames: Int,
                        val sample_aspect_ratio: String,
                        val display_aspect_ratio: String,
                        val pix_fmt: String,
                        val level: Int,
                        val color_range: String,
                        val chroma_location: String,
                        val field_order: String,
                        val refs: Int,
                        val r_frame_rate: String,
                        val avg_frame_rate: String,
                        val time_base: String,
                        val start_pts: Int,
                        val start_time: String,
                        val extradata_size: Int,
                        val disposition: Disposition,
                        val tags: Tags): Serializable
